version: '2'
services:
  gerrit:
    image: "openfrontier/gerrit"
    ports:
     - "8080:8080"
     - "29418:29418"
    volumes:
     - ./gerrit:/var/gerrit/review_site
    environment:
     - AUTH_TYPE=DEVELOPMENT_BECOME_ANY_ACCOUNT
     - GERRIT_INIT_ARGS=--install-plugin=download-commands
